config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/dtgeoeu-wp6-tsunamis/tsunami-digital-twin:
      branch: miniST610106
      repo: https://github.com/dtgeoeu-wp6-tsunamis/tsunami-digital-twin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/dtgeoeu-wp6-tsunamis/tsunami-digital-twin git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-ruby-cassowary.sh
        container: qc.acc_lousy-plum-chipmunk
  QC.Doc:
    repos:
      github.com/dtgeoeu-wp6-tsunamis/tsunami-digital-twin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-lilac-corgi.sh
        container: qc.doc_wimpy-violet-saola
      github.com/dtgeoeu-wp6-tsunamis/tsunami-digital-twin git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-chestnut-corgi.sh
        container: qc.doc_lanky-taupe-javanese
  QC.Lic:
    repos:
      github.com/dtgeoeu-wp6-tsunamis/tsunami-digital-twin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-sangria-heron.sh
        container: qc.lic_craggy-red-peccary
  QC.Sec:
    repos:
      github.com/dtgeoeu-wp6-tsunamis/tsunami-digital-twin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-asparagus-macaque.sh
        container: qc.sec_shaggy-sepia-capuchin
  QC.Sty:
    repos:
      github.com/dtgeoeu-wp6-tsunamis/tsunami-digital-twin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-vermilion-vole.sh
        container: qc.sty_fuzzy-asparagus-binturong
      github.com/dtgeoeu-wp6-tsunamis/tsunami-digital-twin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-cream-wolf.sh
        container: qc.sty_stealthy-dandelion-frise
  QC.Uni:
    repos:
      github.com/dtgeoeu-wp6-tsunamis/tsunami-digital-twin pytest:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-burgundy-audemer.sh
        container: qc.uni_lanky-lilac-wombat
  QC.Ver:
    repos:
      github.com/dtgeoeu-wp6-tsunamis/tsunami-digital-twin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-teal-sheepdog.sh
        container: qc.ver_lovely-amaranth-bison
timeout: 5400
