config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/dtgeoeu-wp6-tsunamis/tsunami-digital-twin:
      branch: miniST610106
      repo: https://github.com/dtgeoeu-wp6-tsunamis/tsunami-digital-twin
      subfolder: DTC61/WF6102/ST610206/src
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/dtgeoeu-wp6-tsunamis/tsunami-digital-twin git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-lemon-meerkat.sh
        container: qc.acc_cozy-corn-burmese
  QC.Doc:
    repos:
      github.com/dtgeoeu-wp6-tsunamis/tsunami-digital-twin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-russet-otter.sh
        container: qc.doc_snappy-cream-tortoise
      github.com/dtgeoeu-wp6-tsunamis/tsunami-digital-twin git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-corn-boar.sh
        container: qc.doc_gamy-rust-gecko
  QC.Lic:
    repos:
      github.com/dtgeoeu-wp6-tsunamis/tsunami-digital-twin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-ecru-guppy.sh
        container: qc.lic_wimpy-corn-reindeer
  QC.Sec:
    repos:
      github.com/dtgeoeu-wp6-tsunamis/tsunami-digital-twin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-cerise-quokka.sh
        container: qc.sec_smelly-black-dingo
  QC.Sty:
    repos:
      github.com/dtgeoeu-wp6-tsunamis/tsunami-digital-twin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-buff-mule.sh
        container: qc.sty_whiny-xanthic-beetle
      github.com/dtgeoeu-wp6-tsunamis/tsunami-digital-twin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-rust-neanderthal.sh
        container: qc.sty_cloudy-alizarin-dormouse
  QC.Uni:
    repos:
      github.com/dtgeoeu-wp6-tsunamis/tsunami-digital-twin commands:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-sepia-robin.sh
        container: qc.uni_lumpy-asparagus-bongo
  QC.Ver:
    repos:
      github.com/dtgeoeu-wp6-tsunamis/tsunami-digital-twin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-scarlet-barb.sh
        container: qc.ver_hazy-chartreuse-chinchilla
timeout: 5400
